#cloud-config

packages:
  - curl
  - git
  - git-flow
  - docker.io
  - flameshot
  - gnome-tweaks
  - chromium
  - fonts-firacode
  - inkscape
  - gimp

snaps:
  - name: discord
    classic: true
  - name: redis-insight
    classic: true

runcmd:
  # Baixa os scripts
  - wget -qO /usr/local/bin/nvm.sh https://raw.githubusercontent.com/CeruttiMaicon/my-ubuntu-dev/main/scripts/nvm.sh
  - wget -qO /usr/local/bin/vscode.sh https://raw.githubusercontent.com/CeruttiMaicon/my-ubuntu-dev/main/scripts/vscode.sh
  - wget -qO /usr/local/bin/zsh.sh https://raw.githubusercontent.com/CeruttiMaicon/my-ubuntu-dev/main/scripts/zsh.sh
  - wget -qO /usr/local/bin/docker.sh https://raw.githubusercontent.com/CeruttiMaicon/my-ubuntu-dev/main/scripts/docker.sh
  - wget -qO /usr/local/bin/docker-compose-v2.sh https://raw.githubusercontent.com/CeruttiMaicon/my-ubuntu-dev/main/scripts/docker-compose-v2.sh
  - wget -qO /usr/local/bin/eza-icons-terminal.sh https://raw.githubusercontent.com/CeruttiMaicon/my-ubuntu-dev/main/scripts/eza-icons-terminal.sh
  - wget -qO /usr/local/bin/powerlevel10k.sh https://raw.githubusercontent.com/CeruttiMaicon/my-ubuntu-dev/main/scripts/powerlevel10k.sh
  - wget -qO /usr/local/bin/warp-terminal.sh https://raw.githubusercontent.com/CeruttiMaicon/my-ubuntu-dev/main/scripts/warp-terminal.sh
  - wget -qO /usr/local/bin/spotify.sh https://raw.githubusercontent.com/CeruttiMaicon/my-ubuntu-dev/main/scripts/spotify.sh
  - wget -qO /usr/local/bin/1password.sh https://raw.githubusercontent.com/CeruttiMaicon/my-ubuntu-dev/main/scripts/1password.sh

  # Permite execução dos scripts
  - chmod +x /usr/local/bin/*.sh

  # Executa os scripts
  - bash /usr/local/bin/nvm.sh
  - bash /usr/local/bin/vscode.sh
  - bash /usr/local/bin/zsh.sh
  - bash /usr/local/bin/docker.sh
  - bash /usr/local/bin/docker-compose-v2.sh
  - bash /usr/local/bin/eza-icons-terminal.sh
  - bash /usr/local/bin/powerlevel10k.sh
  - bash /usr/local/bin/warp-terminal.sh
  - bash /usr/local/bin/spotify.sh
  - bash /usr/local/bin/1password.sh
